[package]
name = "mnempass"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
description = "mnempass - mnemonic password tool"
homepage = "https://github.com/mnempass/mnempass"
repository = "https://github.com/mnempass/mnempass"
readme = "README.md"


[dependencies]
